[build]
  publish = "."
  command = "echo 'No build command required'"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  node_version = "18.x"

[build.environment]
  NODE_OPTIONS = "--experimental-modules"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200