[build]
  publish = "."
  command = "echo 'No build command required'"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions.node_version]
  nodejs = "18.x"

[build.environment]
  NODE_OPTIONS = "--enable-source-maps --experimental-json-modules"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200